config/routes.rb
Rails.application.routes.draw do

  # devise_for :users, controllers: { registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks' }
  # devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#start"
  get    '/about',   to: 'home#about'
  resources :microposts, only: %i[create destroy index show] do
    resources :likes, only: %i[create destroy]
  end
  get '/users/auth/facebook/callback', to: redirect('/auth/facebook/callback')
  devise_for :users, controllers: { registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks' }, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  resources :comments, only: [:create, :destroy, :update, :edit]
  authenticated :user do
    get 'users/:user_id/friends', to: 'users#friends', as: 'users_friends'
    get 'users', to: 'users#index', as: 'users'
    get 'friend_requests/', to: 'users#friend_requests', as: 'user_friend_requests'
    post 'friend_request/:requestee_user_id', to: 'friendships#create', as: 'friend_request'
    put 'friend_requests/:requestee_user_id/:requested_user_id', to: 'friendships#accept', as: 'accept_friend_request'
    delete 'friend_requests/:requester_user_id/:requestee_user_id', to: 'friendships#delete', as: 'delete_friend_request'
  end

end

app/views/partials/_buddies.html.erb
<% @user.friends.each do |friend| %>
  <li>
    <%= gravatar_for friend, size: 50 %>
    <%= friend.name %>
  </li>
<% end %>

<% 
=begin %>
<% if @pal_items.any? %>
  <ol>
    <%= render @pal_items %>
  </ol>

<% end %>
<% 
=end %>

app/views/partials/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/partials/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/partials/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 4) {
      alert('Maximum file size is 4MB. Please choose a smaller file.');
    }
  });
</script>

app/views/partials/_nav.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="#">
      <p>SocietalBook</p>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to 'Home', root_path, class: "navbar-item"%>
      <% if user_signed_in? %>
        <%= link_to 'Micropost', microposts_path, class: "navbar-item"%>
        <%= link_to 'Friends List', users_friends_path(current_user), class: "navbar-item"%>
        <%= link_to 'Users',users_path, class: "navbar-item"%>
      <%end%> 

      <% if user_signed_in? %>
        <a class="navbar-item" href="<%=user_friend_requests_path%>">
          <p>Notifications</p>
          &nbsp;<span class="tag is-danger is-rounded"> <%=current_user.friend_requests.count%></span>
        </a>
      <%end%>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>
        <div class="navbar-dropdown">
          <li class="navbar-item">
            <%= link_to "About",   about_path %>
          </li>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Need help?
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
        			<%= link_to 'Sign out', destroy_user_session_path, class: "button is-primary", method: :delete %>
          <% else %>
              <strong>
                <%= link_to 'Sign up', new_user_registration_path, class: "button is-primary" %>
              </strong>
              <strong>
                <%= link_to 'Sign in', new_user_session_path, class: "button is-light" %>
              </strong>
        	<% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/partials/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a>
    <strong id="following" class="stat">
      <%= @user.friends.count %>
    </strong>
    <%= (@user.friends.count) == 1 ? 'Friend' : 'Friends'%>
  </a>
</div>

app/views/partials/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>