config/routes.rb
Rails.application.routes.draw do

  # devise_for :users, controllers: { registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks' }
  # devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#start"
  get    '/about',   to: 'home#about'
  resources :microposts, only: %i[create destroy index show] do
    resources :likes, only: %i[create destroy]
  end
  get '/users/auth/facebook/callback', to: redirect('/auth/facebook/callback')
  devise_for :users, controllers: { registrations: 'users/registrations', :omniauth_callbacks => 'users/omniauth_callbacks' }, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  resources :comments, only: [:create, :destroy, :update, :edit]
  authenticated :user do
    get 'users/:user_id/friends', to: 'users#friends', as: 'users_friends'
    get 'users', to: 'users#index', as: 'users'
    get 'friend_requests/', to: 'users#friend_requests', as: 'user_friend_requests'
    post 'friend_request/:requestee_user_id', to: 'friendships#create', as: 'friend_request'
    put 'friend_requests/:requestee_user_id/:requested_user_id', to: 'friendships#accept', as: 'accept_friend_request'
    delete 'friend_requests/:requester_user_id/:requestee_user_id', to: 'friendships#delete', as: 'delete_friend_request'
  end

end

app/models/micropost.rb
# frozen_string_literal: true

class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  mount_uploader :picture, PictureUploader
  validates :content, length: { maximum: 255 }, presence: true
  validate :picture_size

  private

  # Validates the size of an uploaded picture.
  def picture_size
    errors.add(:picture, 'should be less than 5MB') if picture.size > 5.megabytes
  end
end

app/controllers/microposts_controller.rb
# frozen_string_literal: true

class MicropostsController < ApplicationController
  before_action :find_post, except: %i[new create index]
  before_action :authenticate_user!, only: %i[new create edit update destroy]

  def index
    @posts = Micropost.all
    @pagy, @feeds = pagy(current_user.feed, items: 5)
    @post = Micropost.new
    @comments = Comment.all
    @comment = Comment.new
    @likes = Like.all
  end

  def show
  end

  def edit
  end

  def update
    @post.update(content: params[:post][:content])

    redirect_to @post
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = 'Micropost created!'
      redirect_to microposts_url
    else
      flash[:error] = 'Micropost created!'
      render root_url
    end
  end

  def destroy
    @post.destroy
    redirect_to microposts_path
  end

  def find_post
    @post = Micropost.find(params[:id])
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :picture)
  end
end

app/helpers/microposts_helper.rb
# frozen_string_literal: true

module MicropostsHelper
end

app/views/microposts/_feed.html.erb
<% if @feeds %>
<% @feeds.each do |p| %>
<article class="media">
  <figure class="media-left">
    <p class="image is-64x64">
      <%= link_to gravatar_for(current_user, size: 50)%>
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= p.user.name %></strong>
        <br>
        <%= p.content %>
        <br>
        <%= image_tag p.picture.url if p.picture? %>
      </p>
      <span class="timestamp">
          Posted <%= time_ago_in_words(p.created_at) %> ago.
      </span>
    </div>
    <nav class="level is-mobile">
      <div class="level-left">
        <a class="level-item">
          <span class="icon is-small">
          <% pre_like = p.likes.find { |like| like.user_id == current_user.id} %>
          <% if pre_like %>
            <%= link_to fa_icon("thumbs-down"), micropost_like_path(p.id, pre_like), method: :delete %>
          <% else %>
            <%= link_to fa_icon("thumbs-up"), micropost_likes_path(micropost_id: p.id), method: :post %>
          <% end %>
          </span>
          <p><%= p.likes.count %> <%= (p.likes.count) == 1 ? 'Like' : 'Likes'%></p>
        </a>
        
      </div>
      <div class="media-right">
      <% if p.user.id == current_user.id %>
        <%= link_to fa_icon("trash"), p, method: :delete %>
      <% else %>
        <%= link_to fa_icon(" ") %>
      <% end %>
      </div>
    </nav>

    <% @comments.each do |c| %>
    <% if p.id == c.micropost_id %>
      <article class="media">
        <figure class="media-left">
          <p class="image is-64x64">
            <%= link_to gravatar_for(current_user, size: 50)%>
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= c.user.name %></strong>
              <br>
              <%= c.replay %>
            </p>
          </div>
          <nav class="level is-mobile">
            <div class="level-left">
              <a class="level-item">
                <span class="icon is-small"><%=fa_icon "reply-all"%></span>
              </a>
              <a class="level-item">
                <span class="icon is-small"><%=fa_icon "retweet"%></span>
              </a>
              <a class="level-item">
                <span class="icon is-small"><%=fa_icon "thumbs-down"%></span>
              </a>
            </div>
          </nav>
        </div>
        <% if c.user.id == current_user.id %>
          <%= link_to fa_icon("trash"), c, method: :delete %>
        <% else %>
          <%= link_to fa_icon(" ") %>
        <% end %>
      </article>
    <%end%>
    <%end%>
    <%= form_with(model: @comment, local: true) do |c| %>

      <div class="field">
        <%= c.hidden_field :user_id, value:current_user.id%>
        <%= c.hidden_field :micropost_id, value:p.id%>
        <%= c.label :replay, "What is your comment ?", class: "label" %>
        <%= c.text_area :replay, class: "textarea", rows: "2", placeholder: 'Add a comment...' %>
      </div>

      <div>
        <%= c.submit "Save", class: "button is-dark is-fullwidth" %>
      </div>
    <% end %>
  </div>
</article><br>
<%end%>
<% else %>
<% end %>
<%= pagy_bulma_nav(@pagy).html_safe %>

app/views/microposts/_form.html.erb
<%= form_with(model: @post, local: true) do |form| %>

	<div class="field">
		<%= form.label :content, "What's on your mind ?", class: "label" %>
		<%= form.text_area :content, class: "textarea", placeholder: 'Add a micropost...' %>
	</div>

	<div>
		<%= form.submit "Submit", class: "button is-dark is-fullwidth" %>
	</div>
	<br>
	<span class="picture">
    <%= form.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
	
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/microposts/_post.html.erb
<div class="card padding margin-top" >
	<p class="tect-secondary"><%= post.created_at%></p>
	<%= link_to  "Show more...", post %>
</div>

app/views/microposts/edit.html.erb
<div class="small-container center-block">
	<%= render "microposts/form" %>
</div>

app/views/microposts/index.html.erb
<div class="hero">
  <div class="hero-body">
    <div class="container">
      <% if signed_in? %>
        <div class="columns">
          <div class="column is-one-third">
            <section class="micropost_form">
              <%= render "form" %>
            </section>
          </div>
          <div class="column is-two-third">
            <h3>Micropost Feed</h3>
            <%= render "feed" %>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/microposts/new.html.erb
<div class="columns is-mobile">
  <div class="column is-half is-offset-one-quarter">
	<%= render "microposts/form" %>
	</div>
</div>

app/views/microposts/show.html.erb
<div>
	<%= @post.content %>
</div>

<div>
	<%= link_to "Delete Post", @post, method: :delete%>
</div>